apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rasa-action-server-app
  namespace: argocd
spec:
  project: default
  source:
    chart: rasa-action-server
    repoURL: https://helm.rasa.com
    targetRevision: HEAD
    helm:
      releaseName: rasa-action-server
      parameters:
        - name: registry
          value: docker.io/klpanagi
        - name: image.name
          value: rasa-action-server
        - name: image.tag
          value: caeba993b9fd68e1d96a8ab705b6d03ddfcaf1a1
  destination:
    server: "https://kubernetes.default.svc"
    namespace: rasa
