apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rasa-action-server
  namespace: argocd
spec:
  project: default
  source:
    chart: rasa-action-server
    repoURL: https://helm.rasa.com
    targetRevision: 1.0.3
    helm:
      releaseName: rasa-action-server
      parameters:
        - name: registry
          value: docker.io/klpanagi
        - name: image.name
          value: rasa-action-server
        - name: image.tag
          value: 0f4269e425041bf4653f3e9a300ca454bf1e4cdf
  destination:
    server: "https://kubernetes.default.svc"
    namespace: rasa
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
