on:
  push:
    branches:
      - main
    paths:
    - 'actions/**'
    - '.github/workflows/action_server.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Action Server image and push to DockerHub
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    # - name: Login to GitHub Container Registry
    #   uses: docker/login-action@v2
    #   with:
    #     registry: ghcr.io
    #     username: ${{ github.repository_owner }}
    #     password: ${{ secrets.GITHUB_TOKEN }}

    - id: action_server
      name: Build an action server with custom actions and Upload to Docker Registry
      uses: RasaHQ/action-server-gha@main
      # Full list of parameters: https://github.com/RasaHQ/action-server-gha/tree/master#input-arguments
      with:
        actions_directory: actions/
        requirements_file: actions/requirements.txt
        docker_image_name: 'klpanagi/rasa-action-server'
        docker_registry_login: ${{ secrets.DOCKER_HUB_LOGIN }}
        docker_registry_password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        docker_image_tag: ${{ github.sha }}

  update_tag:
    needs: [ build ]
    name: Update application manifest for CD to use last commited rasa-action-server image
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Update Application manifest - Set image tag
      id: update_application_manifest
      uses: mikefarah/yq@master
      with:
        cmd: yq eval '.spec.source.helm.parameters[2].value = "${{ github.sha }}"' -i manifests/application.yaml

    - name: Commit application manifest changes
      id: commit_image_tag_changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Apply image tag changes
