on:
  push:
    branches:
      - main
    paths:
    - 'actions/**'
    - '.github/workflows/action_server.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Action Server image and push to DockerHub
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    # - name: Login to GitHub Container Registry
    #   uses: docker/login-action@v2
    #   with:
    #     registry: ghcr.io
    #     username: ${{ github.repository_owner }}
    #     password: ${{ secrets.GITHUB_TOKEN }}

    - id: action_server
      name: Build an action server with custom actions and Upload to Docker Registry
      uses: RasaHQ/action-server-gha@main
      # Full list of parameters: https://github.com/RasaHQ/action-server-gha/tree/master#input-arguments
      with:
        actions_directory: actions/
        requirements_file: actions/requirements.txt
        docker_image_name: 'klpanagi/rasa-action-server'
        docker_registry_login: ${{ secrets.DOCKER_HUB_LOGIN }}
        docker_registry_password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        # More details about github context:
        # https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#github-context
        #
        # github.sha - The commit SHA that triggered the workflow run
        docker_image_tag: ${{ github.sha }}
